import type { IconType } from 'react-icons';
import {
  GiTomato,
  GiGarlic,
  GiCarrot,
  GiBroccoli,
  GiBellPepper,
  GiChiliPepper,
  GiPotato,
  GiMushroom,
  GiCabbage,
  GiAsparagus,
  GiBeet,
  GiCorn,
  GiPumpkin,
  GiLemon,
  GiAvocado,
  GiGrapes,
  GiBanana,
  GiOrange,
  GiStrawberry,
  GiPineapple,
  GiCoconuts,
  GiPeach,
  GiWatermelon,
  GiCherry,
  GiRaspberry,
  GiKiwiFruit,
  GiChicken,
  GiCow,
  GiPig,
  GiSheep,
  GiBacon,
  GiSausage,
  GiFishCooked,
  GiShrimp,
  GiBigEgg,
  GiCheeseWedge,
  GiMilkCarton,
  GiButter,
  GiFlour,
  GiSugarCane,
  GiBowlOfRice,
  GiNoodles,
  GiBreadSlice,
  GiHoneyJar,
  GiOlive,
  GiPeanut,
  GiAlmond,
  GiPeas,
  GiWheat,
  GiChocolateBar,
  GiWineBottle,
  GiKetchup,
} from 'react-icons/gi';

// A curated set of common cooking ingredients. Each has a matching icon where
// a good one exists in the icon set; ingredients without one (e.g. Onion,
// Tofu — there's no dedicated icon for them anywhere in react-icons) fall
// back to a monogram tile in the UI rather than forcing a mismatched icon.
export interface IngredientDef {
  name: string;
  icon?: IconType;
}

export const ingredientLibrary: IngredientDef[] = [
  // Proteins
  { name: 'Chicken', icon: GiChicken },
  { name: 'Beef', icon: GiCow },
  { name: 'Pork', icon: GiPig },
  { name: 'Lamb', icon: GiSheep },
  { name: 'Turkey' },
  { name: 'Bacon', icon: GiBacon },
  { name: 'Sausage', icon: GiSausage },
  { name: 'Fish', icon: GiFishCooked },
  { name: 'Shrimp', icon: GiShrimp },
  { name: 'Egg', icon: GiBigEgg },
  { name: 'Tofu' },

  // Vegetables
  { name: 'Tomato', icon: GiTomato },
  { name: 'Onion' },
  { name: 'Garlic', icon: GiGarlic },
  { name: 'Carrot', icon: GiCarrot },
  { name: 'Broccoli', icon: GiBroccoli },
  { name: 'Bell Pepper', icon: GiBellPepper },
  { name: 'Chili Pepper', icon: GiChiliPepper },
  { name: 'Potato', icon: GiPotato },
  { name: 'Mushroom', icon: GiMushroom },
  { name: 'Cabbage', icon: GiCabbage },
  { name: 'Asparagus', icon: GiAsparagus },
  { name: 'Beet', icon: GiBeet },
  { name: 'Corn', icon: GiCorn },
  { name: 'Pumpkin', icon: GiPumpkin },
  { name: 'Spinach' },
  { name: 'Lettuce' },
  { name: 'Cucumber' },
  { name: 'Zucchini' },
  { name: 'Eggplant' },

  // Fruits
  { name: 'Lemon', icon: GiLemon },
  { name: 'Avocado', icon: GiAvocado },
  { name: 'Grape', icon: GiGrapes },
  { name: 'Banana', icon: GiBanana },
  { name: 'Orange', icon: GiOrange },
  { name: 'Strawberry', icon: GiStrawberry },
  { name: 'Pineapple', icon: GiPineapple },
  { name: 'Coconut', icon: GiCoconuts },
  { name: 'Peach', icon: GiPeach },
  { name: 'Watermelon', icon: GiWatermelon },
  { name: 'Cherry', icon: GiCherry },
  { name: 'Raspberry', icon: GiRaspberry },
  { name: 'Kiwi', icon: GiKiwiFruit },

  // Dairy & pantry
  { name: 'Cheese', icon: GiCheeseWedge },
  { name: 'Milk', icon: GiMilkCarton },
  { name: 'Butter', icon: GiButter },
  { name: 'Yogurt' },
  { name: 'Flour', icon: GiFlour },
  { name: 'Sugar', icon: GiSugarCane },
  { name: 'Rice', icon: GiBowlOfRice },
  { name: 'Pasta', icon: GiNoodles },
  { name: 'Bread', icon: GiBreadSlice },
  { name: 'Honey', icon: GiHoneyJar },
  { name: 'Olive', icon: GiOlive },
  { name: 'Peanut', icon: GiPeanut },
  { name: 'Almond', icon: GiAlmond },
  { name: 'Peas', icon: GiPeas },
  { name: 'Beans' },
  { name: 'Wheat', icon: GiWheat },
  { name: 'Chocolate', icon: GiChocolateBar },
  { name: 'Wine', icon: GiWineBottle },
  { name: 'Ketchup', icon: GiKetchup },
];
